# **📚 Librerías en Python - Expandiendo la magia**

<div style="border: 3px solid #FF6B6B; padding: 15px; border-radius: 10px; background-color: #FFE5E5;">

# 🔧 ¿Qué son las librerías?

Las librerías son **módulos de código especializado** que otros desarrolladores han creado para resolver problemas específicos. En lugar de programar todo desde cero, puedes aprovechar estas herramientas poderosas que extienden las capacidades básicas de Python.

**💡 Concepto clave:** Las librerías proveen **funcionalidad específica** para tareas particulares - desde manipular datos hasta procesar imágenes, reconocer texto, o crear aplicaciones web.

## 🎯 ¿Por qué son tan importantes?

- **Ahorro de tiempo:** No reinventes la rueda
- **Código probado:** Miles de desarrolladores ya las han usado
- **Funcionalidad avanzada:** Capacidades que tomarían años desarrollar
- **Comunidad activa:** Documentación, ejemplos y soporte

## 🌟 Librerías fundamentales para ciencia de datos:

**🐼 pandas** - El Swiss Army knife de los datos
- Manipulación y análisis de datos estructurados
- Leer/escribir Excel, CSV, JSON, bases de datos
- Filtrado, agrupación, y transformación de datos

**🔢 numpy** - Computación numérica de alto rendimiento
- Operaciones matemáticas vectorizadas súper rápidas
- Fundamento de casi todas las librerías científicas
- Álgebra lineal, estadística, y arrays multidimensionales

**📊 matplotlib** - Visualización profesional
- Gráficos científicos y presentaciones
- Charts, histogramas, scatter plots, mapas de calor
- Personalización completa de estilos y formatos

</div>

<div style="border: 3px solid #673AB7; padding: 15px; border-radius: 10px; background-color: #EDE7F6;">

# 🚀 El universo de librerías Python - ¡Prepárate para sorprenderte!

Python tiene más de **300,000 librerías** disponibles. Aquí tienes una selección fascinante de lo que puedes hacer (y algunas travesuras que puedes crear):

## 🎥 **Multimedia y Contenido Digital**

**🎬 OpenCV** - Visión por computadora y procesamiento de imágenes
- Detectar rostros en fotos automáticamente *(¡Adiós filtros manuales!)*
- Crear filtros tipo Instagram en tiempo real *(Competencia directa a Snapchat)*
- Reconocer objetos en videos en vivo *(Tu propia matriz de detección)*

**🎵 librosa** - Análisis de audio avanzado
- Analizar canciones y extraer el ritmo *(¿Es reggaetón o no?)*
- Reconocer géneros musicales automáticamente *(Fin de las discusiones musicales)*  
- Detectar emociones en la voz humana *(¡Detector de mentiras casero!)*

**📷 Pillow (PIL)** - Manipulación de imágenes
- Redimensionar miles de fotos automáticamente *(Adiós tardes perdidas)*
- Crear memes con texto superpuesto *(Fábrica de memes automática)*
- Convertir formatos de imagen en lote *(Batch processing como un pro)*

**🎞️ moviepy** - Edición de video programática
- Crear videos automáticamente desde fotos *(Montajes épicos sin esfuerzo)*
- Agregar subtítulos y efectos *(Tu propio estudio de edición)*
- Comprimir videos para redes sociales *(Optimización ninja)*

## 🧠 **Inteligencia Artificial y Machine Learning**

**🤖 scikit-learn** - Machine Learning para todos
- Predecir precios de casas basado en características *(¡Tu propio Zillow!)*
- Clasificar emails como spam o no spam *(Adiós promociones raras)*
- Recomendar productos como Netflix o Amazon *(Motor de recomendaciones personal)*

**🔥 TensorFlow/PyTorch** - Deep Learning profesional
- Crear chatbots inteligentes *(Competencia a ChatGPT casera)*
- Reconocer objetos en imágenes como Tesla Autopilot *(Visión artificial level: experto)*
- Generar arte y música con IA *(Picasso y Mozart digitales)*

**🗣️ SpeechRecognition** - Reconocimiento de voz
- Convertir audio a texto automáticamente *(Transcriptor personal)*
- Crear asistentes virtuales como Siri *(Tu propio Jarvis)*
- Transcribir entrevistas y reuniones *(Nunca más tomar notas a mano)*

**📝 spaCy/NLTK** - Procesamiento de lenguaje natural
- Analizar sentimientos en reseñas de productos *(¿La gente realmente lo ama?)*
- Extraer información de documentos legales *(Leer contratos sin abogado)*
- Traducir idiomas automáticamente *(Google Translate en tu código)*

## 🌐 **Web y APIs**

**🌍 requests** - Interactuar con internet
- Obtener datos del clima en tiempo real *(Tu meteorólogo personal)*
- Descargar información de redes sociales *(Social media analytics DIY)*
- Conectar con APIs de bancos y servicios *(Fintech en casa)*

**🕸️ BeautifulSoup** - Web scraping inteligente
- Extraer precios de productos desde e-commerce *(Comparador de precios automático)*
- Monitorear noticias automáticamente *(Tu propio Google News)*
- Recopilar datos de investigación desde webs *(Investigador digital incansable)*

**⚡ FastAPI/Flask** - Crear aplicaciones web
- Construir tu propia red social *(Facebook casero, pero mejor)*
- Crear APIs para apps móviles *(Backend de startup en una noche)*
- Desarrollar tiendas online *(E-commerce desde cero)*

## 📊 **Visualización Avanzada**

**🎨 seaborn** - Gráficos estadísticos hermosos
- Visualizar correlaciones en datos complejos *(Patrones ocultos revelados)*
- Crear dashboards interactivos *(Tableros de control profesionales)*
- Mapas de calor y distribuciones elegantes *(Arte estadístico)*

**🌟 plotly** - Visualizaciones interactivas
- Gráficos 3D que puedes rotar *(Datos en realidad virtual)*
- Dashboards interactivos para empresas *(Presentaciones que impresionan)*
- Mapas geográficos con datos en tiempo real *(Epidemiólogo amateur)*

**🗺️ folium** - Mapas interactivos
- Crear mapas como Google Maps *(Cartógrafo digital)*
- Visualizar datos geográficos *(GPS con superpoderes)*
- Tracking de rutas y ubicaciones *(Stalker... ehh, analista de ubicaciones)*

## 📄 **Documentos y Automatización**

**📋 openpyxl** - Excel sin Excel
- Generar reportes empresariales automáticamente *(Adiós noches de Excel)*
- Procesar miles de hojas de cálculo *(Computadora trabajando 24/7)*
- Crear gráficos y tablas dinámicas *(Excel ninja mode)*

**📑 PyPDF2** - Manipulación de PDFs
- Fusionar PDFs automáticamente *(Combinador de documentos)*
- Extraer texto de documentos escaneados *(OCR básico pero efectivo)*
- Crear formularios PDF programáticamente *(Generador de papeleos)*

**📧 smtplib** - Automatización de emails
- Enviar reportes automáticos por email *(Secretario virtual)*
- Crear newsletters personalizados *(Marketing automation casero)*
- Notificaciones inteligentes basadas en datos *(Sistema de alertas personal)*

## 🎮 **Entretenimiento y Juegos**

**🎯 pygame** - Desarrollo de videojuegos
- Crear tu propio Tetris o Snake *(Nostalgia programable)*
- Juegos 2D completos con física *(Indie developer en ciernes)*
- Prototipos rápidos de juegos mobile *(Angry Birds casero)*

**🎲 random** - Generación de contenido aleatorio
- Simulaciones de Monte Carlo *(Predicciones estadísticas avanzadas)*
- Generadores de contraseñas seguras *(Fort Knox digital)*
- Juegos de azar y probabilidades *(Casino virtual para estudiar)*

</div>

<div style="border: 3px solid #00BCD4; padding: 15px; border-radius: 10px; background-color: #E0F7FA;">

# 💡 Casos de uso reales - Lo que puedes construir HOY

## 🔥 **Proyectos que te inspirarán:**

### 📱 **Análisis de Redes Sociales**
```python
# Con tweepy + textblob + matplotlib
# ¿Qué opina la gente sobre tu marca favorita?
tweets = obtener_tweets("#Tesla")
sentimientos = analizar_sentimientos(tweets)
graficar_tendencias(sentimientos)
```

### 🏠 **Predictor de Precios Inmobiliarios**
```python
# Con pandas + scikit-learn + requests
# ¿Cuánto debería costar esta casa?
datos_casas = cargar_datos_inmobiliarios()
modelo = entrenar_predictor(datos_casas)
precio_estimado = modelo.predict(nueva_casa)
```

### 📊 **Dashboard Financiero Personal**
```python
# Con yfinance + plotly + dash
# Tu propio Bloomberg personal
acciones = ['AAPL', 'GOOGL', 'TSLA']
datos = descargar_precios(acciones)
crear_dashboard_interactivo(datos)
```

### 🎵 **Recomendador de Música**
```python
# Con spotipy + pandas + scikit-learn
# Tu propio Spotify Discover Weekly
mis_canciones = obtener_historial_spotify()
similares = encontrar_canciones_similares(mis_canciones)
playlist_personalizada = crear_playlist(similares)
```

### 📧 **Detector de Fraude en Emails**
```python
# Con imaplib + nltk + scikit-learn
# Protege tu bandeja de entrada automáticamente
emails = leer_emails_gmail()
clasificacion = detectar_spam(emails)
mover_a_carpeta_spam(emails_sospechosos)
```

### 🎥 **Editor de Video Automático**
```python
# Con moviepy + opencv + numpy
# Crea videos virales automáticamente
clips = cargar_videos_raw()
momentos_destacados = detectar_momentos_emocionantes(clips)
video_final = crear_highlight_reel(momentos_destacados)
```

## 🌟 **¿Cuál te emociona más?**

- **¿Te gusta la música?** → `librosa`, `spotipy`, `pyaudio`
- **¿Eres fanático de los deportes?** → `pandas`, `matplotlib`, `requests` para stats
- **¿Te fascina la fotografía?** → `opencv`, `pillow`, `instagram-api`
- **¿Quieres automatizar tu vida?** → `selenium`, `schedule`, `smtplib`
- **¿Te intrigan las finanzas?** → `yfinance`, `quantlib`, `pandas-datareader`
- **¿Amas los videojuegos?** → `pygame`, `panda3d`, `arcade`

</div>

<div style="border: 3px solid #4ECDC4; padding: 15px; border-radius: 10px; background-color: #E5F9F6;">

# 🛠️ Gestión de librerías - Tu kit de herramientas profesional

## 1️⃣ ¿Tengo instalada una librería?

**Método 1: Verificación con try/except**
```python
try:
    import pandas
    print("✅ pandas está instalada")
except ImportError:
    print("❌ pandas NO está instalada")
```

**Método 2: Verificar versión específica**
```python
import pandas as pd
print(f"📦 Versión de pandas: {pd.__version__}")
```

**Método 3: Listar todas las librerías instaladas**
```bash
pip list
# o para buscar una específica:
pip list | grep pandas
```

## 2️⃣ ¿Cómo instalo una librería?

**🖥️ Desde la terminal/línea de comandos:**
```bash
# Instalación básica
pip install pandas

# Instalación de versión específica
pip install pandas==1.5.0

# Instalación desde requirements.txt
pip install -r requirements.txt

# Instalación con dependencias extra
pip install pandas[all]
```

**📝 En un notebook (como este):**
```python
!pip install pandas
!pip install numpy matplotlib seaborn  # múltiples librerías
!pip install --upgrade pandas  # actualizar a la última versión
```

**🐍 Usando conda (alternativa a pip):**
```bash
conda install pandas
conda install -c conda-forge pandas  # desde un canal específico
```

## 3️⃣ ¿Cómo gestiono las versiones?

**Ver información detallada:**
```bash
pip show pandas  # información completa de la librería
pip check        # verificar dependencias rotas
```

**Actualizar librerías:**
```bash
pip install --upgrade pandas
pip install --upgrade-strategy eager pandas  # actualizar dependencias también
```

**Desinstalar librerías:**
```bash
pip uninstall pandas
pip uninstall -y pandas  # sin confirmación
```

## 4️⃣ Mejores prácticas profesionales

**🔒 Entornos virtuales** (muy recomendado):
```bash
# Crear entorno virtual
python -m venv mi_proyecto
source mi_proyecto/bin/activate  # Linux/Mac
mi_proyecto\Scripts\activate     # Windows

# Instalar librerías en el entorno
pip install pandas numpy matplotlib

# Guardar dependencias
pip freeze > requirements.txt
```

**📋 Archivo requirements.txt**:
```text
pandas==1.5.0
numpy>=1.21.0
matplotlib~=3.5.0
requests
```

</div>

In [7]:
# 🔍 Verificando nuestro arsenal de hechizos... digo, librerías

print("🐰✨ === DIAGNÓSTICO MÁGICO DEL ENTORNO PYTHON ===\n")
print("🎩 *El conejo aprendiz saca su varita y revisa qué hechizos tiene disponibles...*")

# Lista extendida de librerías importantes (hechizos esenciales)
librerias_esenciales = {
    'pandas': 'Manipulación de datos (el hechizo más poderoso)',
    'numpy': 'Computación numérica (matemáticas mágicas)',
    'matplotlib': 'Visualización básica (crear gráficos hermosos)',
    'seaborn': 'Visualización estadística (gráficos de lujo)',
    'requests': 'HTTP y APIs (hablar con internet)',
    'PIL': 'Procesamiento de imágenes (photoshop de Python)',
    'sklearn': 'Machine Learning (inteligencia artificial casera)'
}

print("📋 HECHIZOS ESENCIALES EN TU GRIMORIO:")
print("-" * 70)

instaladas = []
faltantes = []

for libreria, descripcion in librerias_esenciales.items():
    try:
        modulo = __import__(libreria)
        version = getattr(modulo, '__version__', 'N/A')
        print(f"✅ {libreria:<15} v{version:<10} | {descripcion}")
        instaladas.append(libreria)
    except ImportError:
        print(f"❌ {libreria:<15} {'¡Ups! No está':<10} | {descripcion}")
        faltantes.append(libreria)

print(f"\n📊 RESUMEN DEL ARSENAL:")
print(f"   🎯 Hechizos listos: {len(instaladas)}/{len(librerias_esenciales)}")
print(f"   🔮 Hechizos por aprender: {len(faltantes)}")

if faltantes:
    print(f"\n💡 Para completar tu grimorio, invoca:")
    print(f"   !pip install {' '.join(faltantes)}")
    print(f"   🐰 *El conejo susurra: '¡Con esto serás imparable!'*")
else:
    print(f"\n🎉 ¡INCREÍBLE! Tu grimorio está completo.")
    print(f"   🐰 *El conejo hace una reverencia: '¡Eres un mago de verdad!'*")

print(f"\n🌟 Total de hechizos disponibles en PyPI: 300,000+")
print(f"🚀 ¡Python tiene un hechizo para cada problema del universo!")
print(f"🐰 *'Incluso para hacer que los unicornios programen' - susurra el conejo*")

🐰✨ === DIAGNÓSTICO MÁGICO DEL ENTORNO PYTHON ===

🎩 *El conejo aprendiz saca su varita y revisa qué hechizos tiene disponibles...*
📋 HECHIZOS ESENCIALES EN TU GRIMORIO:
----------------------------------------------------------------------
✅ pandas          v2.2.2      | Manipulación de datos (el hechizo más poderoso)
✅ numpy           v1.26.4     | Computación numérica (matemáticas mágicas)
✅ matplotlib      v3.8.4      | Visualización básica (crear gráficos hermosos)
✅ seaborn         v0.13.2     | Visualización estadística (gráficos de lujo)
✅ requests        v2.32.2     | HTTP y APIs (hablar con internet)
✅ PIL             v10.3.0     | Procesamiento de imágenes (photoshop de Python)
✅ sklearn         v1.4.2      | Machine Learning (inteligencia artificial casera)

📊 RESUMEN DEL ARSENAL:
   🎯 Hechizos listos: 7/7
   🔮 Hechizos por aprender: 0

🎉 ¡INCREÍBLE! Tu grimorio está completo.
   🐰 *El conejo hace una reverencia: '¡Eres un mago de verdad!'*

🌟 Total de hechizos disponibles en PyPI: 300,000+
🚀 ¡Python tiene un hechizo para cada problema del universo!
🐰 *'Incluso para hacer que los unicornios programen' - susurra el conejo*

<div style="border: 3px solid #FF5722; padding: 15px; border-radius: 10px; background-color: #FFEBEE;">

# 🗑️ Gestión Avanzada de Librerías

## 🚮 Desinstalación de librerías

A veces necesitamos liberar espacio o remover librerías que ya no usamos:

```bash
# Desinstalar una librería específica
pip uninstall pandas

# Desinstalar múltiples librerías
pip uninstall pandas numpy matplotlib

# Desinstalar con confirmación automática (no preguntar)
pip uninstall -y pandas

# Ver qué se desinstalaría sin hacerlo realmente
pip uninstall --dry-run pandas
```

## 🔧 Limpieza del entorno

```bash
# Ver librerías huérfanas (sin dependencias)
pip list --not-required

# Limpiar cache de pip (liberar espacio)
pip cache purge

# Ver información de una librería específica
pip show pandas

# Listar librerías desactualizadas
pip list --outdated
```

## ⚠️ Mejores prácticas

- **Entornos virtuales**: Siempre usa entornos virtuales para proyectos
- **Documentación**: Mantén actualizado tu `requirements.txt`
- **Versiones**: Especifica versiones en producción para evitar sorpresas
- **Limpieza**: Revisa y limpia dependencias innecesarias periódicamente

</div>

# **📊 DataFrames - Las tablas mágicas de pandas**

<div style="border: 3px solid #9C27B0; padding: 15px; border-radius: 10px; background-color: #F3E5F5;">

# 🗂️ ¿Qué es un DataFrame?

Un **DataFrame** es como una **hoja de Excel mágica** dentro de Python. Es una tabla con filas y columnas donde puedes almacenar y manipular datos de manera súper eficiente.

**💭 Piénsalo como:**
- Una tabla de Excel, pero con superpoderes 🦸‍♀️
- Una base de datos ligera y fácil de usar
- Una grilla donde cada columna puede tener diferentes tipos de datos

## 🏗️ ¿De dónde vienen los DataFrames?

Los DataFrames se pueden crear desde muchas fuentes:

| 📁 Fuente | 📝 Descripción | 🎯 Ejemplo |
|-----------|----------------|------------|
| **Diccionarios** | Datos creados a mano | `{'nombre': ['Ana', 'Luis'], 'edad': [25, 30]}` |
| **Archivos CSV** | Hojas de cálculo | `pd.read_csv('datos.csv')` |
| **Archivos Excel** | Workbooks de Excel | `pd.read_excel('archivo.xlsx')` |
| **Bases de datos** | SQL, SQLite, etc. | `pd.read_sql()` |
| **APIs web** | Datos de internet | `pd.read_json()` |
| **Listas** | Arrays de Python | `pd.DataFrame(lista_de_listas)` |

</div>

<div style="border: 3px solid #FF9800; padding: 15px; border-radius: 10px; background-color: #FFF3E0;">

# 🎨 ¡Creemos nuestro primer DataFrame!

Vamos a crear una tabla con información de una granja de conejos mágicos. Usaremos un **diccionario** como base.

**🗂️ Estructura del diccionario:**
```python
datos = {
    'columna1': [valor1, valor2, valor3],
    'columna2': [valor1, valor2, valor3]
}
```

**🎯 Resultado:** Una tabla hermosa y organizada donde cada clave del diccionario se convierte en una columna.

</div>

In [8]:
# 🐰 Creando nuestra granja de conejos mágicos (¡sí, mis primos!)

# Primero importamos pandas
import pandas as pd

print("🐰✨ === CREANDO NUESTRO PRIMER DATAFRAME ===\n")
print("🎩 *El conejo aprendiz agita su varita... '¡Abracadabra DataFramus!'*")

# Creamos un diccionario con datos de conejos
# 🐰 *'Estos son mis primos de la granja mágica' - dice el conejo con orgullo*
datos_conejos = {
    'nombre': ['Pelusa', 'Saltarín', 'Copito', 'Brillante', 'Veloz'],
    'color': ['Blanco', 'Marrón', 'Blanco', 'Gris', 'Negro'],
    'edad': [2, 4, 1, 3, 2],
    'peso': [1.5, 2.1, 1.2, 1.8, 1.6],
    'es_magico': [True, False, True, True, False]
}

# Convertimos el diccionario en un DataFrame
df_conejos = pd.DataFrame(datos_conejos)

print("✨ ¡POOF! DataFrame creado exitosamente!")
print(f"📊 Dimensiones: {df_conejos.shape[0]} conejos x {df_conejos.shape[1]} características")
print("🐰 *'¡Son más organizados que mi madriguera!' - exclama el conejo*\n")

# Mostramos nuestro DataFrame
print("🗂️ Nuestra granja de conejos (versión 2.0 de mi familia):")
display(df_conejos)
print("\n🥕 *El conejo susurra: 'Saltarín es mi primo favorito, aunque no sea mágico...'*")

🐰✨ === CREANDO NUESTRO PRIMER DATAFRAME ===

🎩 *El conejo aprendiz agita su varita... '¡Abracadabra DataFramus!'*
✨ ¡POOF! DataFrame creado exitosamente!
📊 Dimensiones: 5 conejos x 5 características
🐰 *'¡Son más organizados que mi madriguera!' - exclama el conejo*

🗂️ Nuestra granja de conejos (versión 2.0 de mi familia):

      nombre   color  edad  peso  es_magico
0     Pelusa  Blanco     2   1.5       True
1   Saltarín  Marrón     4   2.1      False
2     Copito  Blanco     1   1.2       True
3  Brillante    Gris     3   1.8       True
4      Veloz   Negro     2   1.6      False

🥕 *El conejo susurra: 'Saltarín es mi primo favorito, aunque no sea mágico...'*

<div style="border: 3px solid #4CAF50; padding: 15px; border-radius: 10px; background-color: #E8F5E9;">

# 🔍 Explorando nuestro DataFrame

Ahora que tenemos nuestro DataFrame, vamos a explorarlo como verdaderos detectives de datos.

## 🧙‍♂️ Comandos mágicos básicos:

| 🪄 Comando | 📝 Descripción | 🎯 Ejemplo |
|------------|----------------|------------|
| `df.head()` | Muestra las primeras 5 filas | `df_conejos.head()` |
| `df.tail()` | Muestra las últimas 5 filas | `df_conejos.tail()` |
| `df.info()` | Información general del DataFrame | `df_conejos.info()` |
| `df.describe()` | Estadísticas de columnas numéricas | `df_conejos.describe()` |
| `df.shape` | Dimensiones (filas, columnas) | `df_conejos.shape` |
| `df.columns` | Nombres de las columnas | `df_conejos.columns` |

</div>

In [9]:
# 🕵️ Explorando nuestra granja como detectives de datos (¡con lupa mágica!)

print("🔍✨ === EXPLORANDO NUESTRO DATAFRAME ===\n")
print("🐰 *'¡Vamos a investigar a mis primos como verdaderos detectives!' - dice el conejo*")

# 1️⃣ Información general
print("📋 INFORMACIÓN GENERAL:")
print(f"   • Dimensiones: {df_conejos.shape} (más ordenado que mi madriguera)")
print(f"   • Columnas: {list(df_conejos.columns)}")
print(f"   • Total de conejos: {len(df_conejos)} (una familia pequeña pero poderosa)")

print("\n" + "="*60)

# 2️⃣ Primeras filas
print("\n👀 PRIMERAS 3 FILAS (los conejos más famosos):")
display(df_conejos.head(3))
print("🐰 *'Pelusa siempre quiere ser la primera' - suspira el conejo*")

print("\n" + "="*60)

# 3️⃣ Información detallada de tipos de datos
print("\n📊 TIPOS DE DATOS (o 'de qué están hechos mis primos'):")
print(df_conejos.dtypes)
print("🔮 *'Los datos mágicos son booleanos, ¡obvio!' - dice el conejo orgulloso*")

print("\n" + "="*60)

# 4️⃣ Estadísticas de columnas numéricas
print("\n📈 ESTADÍSTICAS NUMÉRICAS (¡las matemáticas mágicas!):")
display(df_conejos.describe())
print("🥕 *'Copito es el más pequeñito, ¡pero no subestimes su magia!' - advierte el conejo*")

🔍✨ === EXPLORANDO NUESTRO DATAFRAME ===

🐰 *'¡Vamos a investigar a mis primos como verdaderos detectives!' - dice el conejo*
📋 INFORMACIÓN GENERAL:
   • Dimensiones: (5, 5) (más ordenado que mi madriguera)
   • Columnas: ['nombre', 'color', 'edad', 'peso', 'es_magico']
   • Total de conejos: 5 (una familia pequeña pero poderosa)

============================================================

👀 PRIMERAS 3 FILAS (los conejos más famosos):

     nombre   color  edad  peso  es_magico
0    Pelusa  Blanco     2   1.5       True
1  Saltarín  Marrón     4   2.1      False
2    Copito  Blanco     1   1.2       True

🐰 *'Pelusa siempre quiere ser la primera' - suspira el conejo*

============================================================

📊 TIPOS DE DATOS (o 'de qué están hechos mis primos'):
nombre        object
color         object
edad           int64
peso         float64
es_magico       bool
dtype: object
🔮 *'Los datos mágicos son booleanos, ¡obvio!' - dice el conejo orgulloso*

============================================================

📈 ESTADÍSTICAS NUMÉRICAS (¡las matemáticas mágicas!):

           edad      peso
count  5.000000  5.000000
mean   2.400000  1.640000
std    1.140175  0.336155
min    1.000000  1.200000
25%    2.000000  1.500000
50%    2.000000  1.600000
75%    3.000000  1.800000
max    4.000000  2.100000

🥕 *'Copito es el más pequeñito, ¡pero no subestimes su magia!' - advierte el conejo*

In [10]:
# 🎯 Operaciones avanzadas con DataFrames (¡las travesuras del conejo!)

print("🚀✨ === MANIPULACIÓN AVANZADA DE DATAFRAMES ===\n")
print("🐰 *'¡Ahora vamos a filtrar a mi familia como si fuéramos paparazzi!' - dice el conejo travieso*")

# 1️⃣ Filtrado de datos
print("🔍 FILTRADO DE DATOS (separando a los especiales):")
print("-" * 50)

# Filtrar conejos mágicos
conejos_magicos = df_conejos[df_conejos['es_magico'] == True]
print("✨ Conejos mágicos (la élite de la familia):")
display(conejos_magicos)
print("🎩 *'¡Estos son mis favoritos!' - guiña el ojo el conejo*")

print("\n" + "="*60)

# Filtrar por edad
print("\n👶 Conejos jóvenes (los bebés rebeldes menores a 3 años):")
conejos_jovenes = df_conejos[df_conejos['edad'] < 3]
display(conejos_jovenes)
print("🍼 *'Copito todavía usa pañal mágico' - ríe el conejo*")

print("\n" + "="*60)

# 2️⃣ Múltiples filtros
print("\n🎯 FILTROS COMBINADOS (¡el combo perfecto!):")
print("-" * 50)

# Conejos blancos Y mágicos
conejos_especiales = df_conejos[(df_conejos['color'] == 'Blanco') & 
                                (df_conejos['es_magico'] == True)]
print("🤍✨ Conejos blancos y mágicos (la crème de la crème):")
display(conejos_especiales)
print("👑 *'Estos son los VIP de la familia' - dice el conejo con orgullo*")

print("\n" + "="*60)

# 3️⃣ Selección de columnas específicas
print("\n📊 SELECCIÓN DE COLUMNAS (como elegir qué chisme contar):")
print("-" * 50)

# Solo nombres y edades
nombres_edades = df_conejos[['nombre', 'edad']]
print("📝 Solo nombres y edades (lo básico para el chismorreo):")
display(nombres_edades)
print("🗣️ *'Con esto ya puedes hacer buenos chismes en la madriguera' - susurra el conejo*")

print("\n" + "="*60)

# 4️⃣ Ordenamiento
print("\n🔤 ORDENAMIENTO (poniendo orden en el caos):")
print("-" * 50)

# Ordenar por edad (de menor a mayor)
por_edad = df_conejos.sort_values('edad')
print("📈 Ordenados por edad (del bebé al veterano):")
display(por_edad)

print("\n📉 Ordenados por peso (de los gorditos a los flaquitos):")
por_peso = df_conejos.sort_values('peso', ascending=False)
display(por_peso)
print("🥕 *'Saltarín come demasiadas zanahorias' - comenta el conejo*")

print("\n🎉 ¡Ya dominas las operaciones básicas con DataFrames!")
print("🐰 *'¡Eres oficialmente un mago de los datos!' - aplaude el conejo*")
print("🎩✨ *'Ahora puedes manipular datos mejor que yo mis trucos de magia'*")

🚀✨ === MANIPULACIÓN AVANZADA DE DATAFRAMES ===

🐰 *'¡Ahora vamos a filtrar a mi familia como si fuéramos paparazzi!' - dice el conejo travieso*
🔍 FILTRADO DE DATOS (separando a los especiales):
--------------------------------------------------
✨ Conejos mágicos (la élite de la familia):

      nombre   color  edad  peso  es_magico
0     Pelusa  Blanco     2   1.5       True
2     Copito  Blanco     1   1.2       True
3  Brillante    Gris     3   1.8       True

🎩 *'¡Estos son mis favoritos!' - guiña el ojo el conejo*

============================================================

👶 Conejos jóvenes (los bebés rebeldes menores a 3 años):

   nombre   color  edad  peso  es_magico
0  Pelusa  Blanco     2   1.5       True
2  Copito  Blanco     1   1.2       True
4   Veloz   Negro     2   1.6      False

🍼 *'Copito todavía usa pañal mágico' - ríe el conejo*

============================================================

🎯 FILTROS COMBINADOS (¡el combo perfecto!):
--------------------------------------------------
🤍✨ Conejos blancos y mágicos (la crème de la crème):

   nombre   color  edad  peso  es_magico
0  Pelusa  Blanco     2   1.5       True
2  Copito  Blanco     1   1.2       True

👑 *'Estos son los VIP de la familia' - dice el conejo con orgullo*

============================================================

📊 SELECCIÓN DE COLUMNAS (como elegir qué chisme contar):
--------------------------------------------------
📝 Solo nombres y edades (lo básico para el chismorreo):

      nombre  edad
0     Pelusa     2
1   Saltarín     4
2     Copito     1
3  Brillante     3
4      Veloz     2

🗣️ *'Con esto ya puedes hacer buenos chismes en la madriguera' - susurra el conejo*

============================================================

🔤 ORDENAMIENTO (poniendo orden en el caos):
--------------------------------------------------
📈 Ordenados por edad (del bebé al veterano):

      nombre   color  edad  peso  es_magico
2     Copito  Blanco     1   1.2       True
0     Pelusa  Blanco     2   1.5       True
4      Veloz   Negro     2   1.6      False
3  Brillante    Gris     3   1.8       True
1   Saltarín  Marrón     4   2.1      False

📉 Ordenados por peso (de los gorditos a los flaquitos):

      nombre   color  edad  peso  es_magico
1   Saltarín  Marrón     4   2.1      False
3  Brillante    Gris     3   1.8       True
4      Veloz   Negro     2   1.6      False
0     Pelusa  Blanco     2   1.5       True
2     Copito  Blanco     1   1.2       True

🥕 *'Saltarín come demasiadas zanahorias' - comenta el conejo*

🎉 ¡Ya dominas las operaciones básicas con DataFrames!
🐰 *'¡Eres oficialmente un mago de los datos!' - aplaude el conejo*
🎩✨ *'Ahora puedes manipular datos mejor que yo mis trucos de magia'*

<div style="border: 3px solid #E91E63; padding: 15px; border-radius: 10px; background-color: #FCE4EC;">

# 🎉 ¡Excelente trabajo!

Has aprendido los fundamentos de las librerías y DataFrames en Python. Ahora puedes:

## ✅ **Lo que ya dominas:**
- 🔮 Qué son las librerías y para qué sirven
- 🛠️ Cómo verificar, instalar y desinstalar librerías
- 📊 Qué es un DataFrame y de dónde vienen los datos
- 🐰 Crear un DataFrame desde un diccionario
- 🔍 Explorar DataFrames con comandos básicos

## 🚀 **Próximos pasos mágicos:**
- Filtrar y manipular datos en DataFrames
- Leer datos desde archivos CSV y Excel
- Crear visualizaciones hermosas con matplotlib
- Operaciones avanzadas con pandas

**💡 Consejo del mago:** ¡Practica creando tus propios DataFrames con datos que te interesen! Pueden ser tus películas favoritas, tu música, o lo que se te ocurra.

</div>

<div style="border: 3px solid #9C27B0; padding: 15px; border-radius: 10px; background-color: #F3E5F5;">

# 🏋️ Ejercicios Prácticos

## 💪 Desafíos para consolidar conocimientos (¡hora de la diversión!)

### 📊 Ejercicio 1: Crea tu propio DataFrame
Crea un DataFrame con datos de tus películas favoritas (título, año, género, calificación):

```python
# Tu código aquí (¡no hagas trampa!)
peliculas = {
    'titulo': ['...', '...', '...'],
    'año': [..., ..., ...],
    'genero': ['...', '...', '...'],
    'calificacion': [..., ..., ...]
}
```

🐰 *El conejo susurra: "Si pones solo películas de superhéroes, no cuenta como variedad"*

### 🔍 Ejercicio 2: Explora tus datos
- Encuentra películas con calificación mayor a 8 *(Los clásicos dignos)*
- Ordena por año de lanzamiento *(Del Jurásico a la era moderna)*
- Selecciona solo título y calificación *(Lo esencial para recomendar)*

🎬 *"¡Bonus si incluyes una película que nadie más conoce!" - dice el conejo con aire de crítico de cine*

### 📚 Ejercicio 3: Investiga una librería nueva
Elige una librería de la lista que vimos y:
1. Investiga su documentación oficial *(Sí, toca leer un poquito)*
2. Instálala en tu entorno *(¡pip install al poder!)*
3. Crea un ejemplo simple de uso *(Experimenta sin miedo)*

🔮 *"Si eliges pygame, puedes crear un juego donde yo sea el protagonista" - guiña el ojo el conejo*

### 🎯 Desafío Extra (para los valientes)
Combina 2-3 librerías para crear algo único:
- `requests` + `pandas` = Analizador de APIs en tiempo real
- `PIL` + `random` = Generador de memes aleatorios  
- `matplotlib` + tus datos = Visualización épica

🚀 *"¡El límite es tu imaginación... y tu paciencia para debuggear!" - ríe el conejo*

</div>

<div style="border: 3px solid #4CAF50; padding: 30px; border-radius: 15px; background-color: #E8F5E9;">

<div style="text-align: center; margin-bottom: 30px;">
<h1>🎓 ¡Felicitaciones! Has completado el Módulo 3</h1>
</div>

<div style="background-color: white; border-radius: 10px; padding: 20px; margin: 20px auto; max-width: 600px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
<h2 style="text-align: center; color: #2E7D32; margin-bottom: 20px;">🗺️ Navegación del Tutorial</h2>

<table style="width: 100%; border-collapse: collapse; margin: 0 auto; font-family: Arial, sans-serif;">
<thead>
<tr style="background-color: #4CAF50; color: white;">
<th style="padding: 12px; text-align: center; border: 1px solid #ddd;">📚 Parte</th>
<th style="padding: 12px; text-align: center; border: 1px solid #ddd;">📝 Contenido</th>
<th style="padding: 12px; text-align: center; border: 1px solid #ddd;">🔗 Enlace</th>
</tr>
</thead>
<tbody>
<tr style="background-color: #f9f9f9;">
<td style="padding: 12px; text-align: center; border: 1px solid #ddd;"><strong>Parte 1</strong></td>
<td style="padding: 12px; text-align: center; border: 1px solid #ddd;">Variables, Operadores Básicos</td>
<td style="padding: 12px; text-align: center; border: 1px solid #ddd;"><a href="Basicos_de_Python.ipynb" style="color: #2E7D32; text-decoration: none;">Ir al Módulo 1</a></td>
</tr>
<tr style="background-color: white;">
<td style="padding: 12px; text-align: center; border: 1px solid #ddd;"><strong>Parte 2</strong></td>
<td style="padding: 12px; text-align: center; border: 1px solid #ddd;">Operadores Avanzados, Control</td>
<td style="padding: 12px; text-align: center; border: 1px solid #ddd;"><a href="Basicos_de_Python_2.ipynb" style="color: #2E7D32; text-decoration: none;">Ir al Módulo 2</a></td>
</tr>
<tr style="background-color: #E8F5E9;">
<td style="padding: 12px; text-align: center; border: 1px solid #ddd;"><strong>Parte 3</strong></td>
<td style="padding: 12px; text-align: center; border: 1px solid #ddd;">Librerías y DataFrames</td>
<td style="padding: 12px; text-align: center; border: 1px solid #ddd;"><strong>¡Estás aquí!</strong> ✨</td>
</tr>
</tbody>
</table>
</div>

<hr style="border: none; height: 2px; background: linear-gradient(to right, #4CAF50, #81C784, #4CAF50); margin: 30px 0;">

<div style="background-color: white; border-radius: 10px; padding: 20px; margin: 20px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
<h2 style="color: #2E7D32; text-align: center; margin-bottom: 20px;">🎯 Lo que has aprendido</h2>
<div style="display: grid; gap: 10px; max-width: 800px; margin: 0 auto;">
<div style="display: flex; align-items: center; padding: 10px; background-color: #f8f9fa; border-radius: 5px;">
<span style="margin-right: 10px;">✅</span>
<span><strong>Ecosistema de librerías Python:</strong> Más de 300,000 librerías disponibles</span>
</div>
<div style="display: flex; align-items: center; padding: 10px; background-color: #f8f9fa; border-radius: 5px;">
<span style="margin-right: 10px;">✅</span>
<span><strong>Gestión profesional:</strong> Instalación, verificación y mantenimiento</span>
</div>
<div style="display: flex; align-items: center; padding: 10px; background-color: #f8f9fa; border-radius: 5px;">
<span style="margin-right: 10px;">✅</span>
<span><strong>Casos de uso reales:</strong> Desde web scraping hasta inteligencia artificial</span>
</div>
<div style="display: flex; align-items: center; padding: 10px; background-color: #f8f9fa; border-radius: 5px;">
<span style="margin-right: 10px;">✅</span>
<span><strong>DataFrames con pandas:</strong> Creación, exploración y manipulación</span>
</div>
<div style="display: flex; align-items: center; padding: 10px; background-color: #f8f9fa; border-radius: 5px;">
<span style="margin-right: 10px;">✅</span>
<span><strong>Filtrado y ordenamiento:</strong> Operaciones esenciales para análisis de datos</span>
</div>
</div>
</div>

<hr style="border: none; height: 2px; background: linear-gradient(to right, #4CAF50, #81C784, #4CAF50); margin: 30px 0;">

<div style="background-color: white; border-radius: 10px; padding: 20px; margin: 20px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
<h2 style="color: #2E7D32; text-align: center; margin-bottom: 20px;">🚀 Próximos pasos</h2>
<div style="display: grid; gap: 10px; max-width: 600px; margin: 0 auto;">
<div style="display: flex; align-items: center; padding: 10px; background-color: #f8f9fa; border-radius: 5px;">
<span style="margin-right: 10px;">🎯</span>
<span><strong>Practica</strong> con los ejercicios propuestos</span>
</div>
<div style="display: flex; align-items: center; padding: 10px; background-color: #f8f9fa; border-radius: 5px;">
<span style="margin-right: 10px;">🔬</span>
<span><strong>Experimenta</strong> con diferentes librerías</span>
</div>
<div style="display: flex; align-items: center; padding: 10px; background-color: #f8f9fa; border-radius: 5px;">
<span style="margin-right: 10px;">🛠️</span>
<span><strong>Crea</strong> tus propios proyectos de datos</span>
</div>
<div style="display: flex; align-items: center; padding: 10px; background-color: #f8f9fa; border-radius: 5px;">
<span style="margin-right: 10px;">📚</span>
<span><strong>Explora</strong> documentación oficial de pandas y numpy</span>
</div>
</div>
</div>

<hr style="border: none; height: 2px; background: linear-gradient(to right, #4CAF50, #81C784, #4CAF50); margin: 30px 0;">

<div style="background-color: white; border-radius: 10px; padding: 20px; margin: 20px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
<h2 style="color: #2E7D32; text-align: center; margin-bottom: 20px;">💡 Recursos adicionales</h2>
<div style="display: grid; gap: 10px; max-width: 600px; margin: 0 auto;">
<div style="display: flex; align-items: center; padding: 10px; background-color: #f8f9fa; border-radius: 5px;">
<span style="margin-right: 10px;">📖</span>
<span><a href="https://pandas.pydata.org/docs/" style="color: #2E7D32; text-decoration: none;">Documentación oficial de pandas</a></span>
</div>
<div style="display: flex; align-items: center; padding: 10px; background-color: #f8f9fa; border-radius: 5px;">
<span style="margin-right: 10px;">🎥</span>
<span><a href="https://www.kaggle.com/learn/pandas" style="color: #2E7D32; text-decoration: none;">Tutoriales interactivos</a></span>
</div>
<div style="display: flex; align-items: center; padding: 10px; background-color: #f8f9fa; border-radius: 5px;">
<span style="margin-right: 10px;">💬</span>
<span><a href="https://python.org.ar/" style="color: #2E7D32; text-decoration: none;">Comunidad Python en español</a></span>
</div>
</div>
</div>

<div style="text-align: center; margin-top: 30px; font-size: 1.2em; color: #2E7D32;">
<strong>¡El mundo de los datos te espera!</strong> 🌟
</div>

</div>